package actors

import utils.Strings;

rule "matchQuery"
  when
  PersonActorProtocol.Query()
  then
  play.Logger.info("Query message. --Logged from Drools Rule named 'matchQuery'.");
end

rule "matchDumpState"
  when
  PersonActorProtocol.DumpState()
  then
  play.Logger.info("DumpState message. --Logged from Drools Rule named 'matchDumpState'.");
end

rule "matchReferral"
  when
  PersonActorProtocol.Referral()
  then
  play.Logger.info("Referral message. --Logged from Drools Rule named 'matchReferral'.");
end

rule "matchAnswer"
  when
  PersonActorProtocol.Answer()
  then
  play.Logger.info("Answer message. --Logged from Drools Rule named 'matchAnswer'.");
end

rule "matchRefusal"
  when
  PersonActorProtocol.Refusal()
  then
  play.Logger.info("Refusal message. --Logged from Drools Rule named 'matchRefusal'.");
end

rule "matchGetNeeds"
  when
  PersonActorProtocol.GetNeeds()
  then
  play.Logger.info("GetNeeds message. --Logged from Drools Rule named 'matchGetNeeds'.");
end